src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java

Refactor ContactListParser to MatchMate Parser

Replace typo

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Omit coursemate info from command result messages

---

docs/diagrams/UiClassDiagram.puml

Update UML diagram for UI coursemate detail card

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/testutil/CourseMateUtil.java

The parser now rejects commands with no space between prefix and argument. 
The add command now does not use the -n prefix.
This closes #24

Change command format for "add"

---

docs/diagrams/UiClassDiagram.puml

Minor error on UML diagram: GroupListPanel incorrectly pointing to Model

Fix UML diagram for UI

---

src/main/java/seedu/address/commons/core/index/Index.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/commons/core/index/IndexTest.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Add hashtag notation for delete and edit

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java

Closes #88, closes #91, closes #92

Improve error and help messages to fix bugs for v1.2b

---

src/main/resources/view/DarkTheme.css

Fix display of tags

---

src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java

fix add member not updated to group UI

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/ContactList.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/coursemate/UniqueCourseMateList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteSkillCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteSkillCommandParserTest.java

Fix invalid hashtag notation and allow substring reference

---

docs/diagrams/ModelClassDiagram.puml
docs/diagrams/StorageClassDiagram.puml

Update UML for storage classes

---

docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java

Fix user guide

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindGroupCommand.java
src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/model/group/ContainsGroupKeywordPredicate.java
src/main/java/seedu/address/model/group/ContainsKeywordPredicate.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java

find-group command, & change from find to find-mate

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/CommandHistory.java
src/test/java/seedu/address/ui/CommandHistoryTest.java

Support saving command history in UI

---

src/main/java/seedu/address/model/group/Group.java
src/main/java/seedu/address/model/skill/Skill.java
src/main/java/seedu/address/storage/JsonAdaptedGroup.java
src/test/java/seedu/address/model/group/GroupTest.java
src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
src/test/java/seedu/address/testutil/TypicalGroups.java

Add skills to the Group model and storage

---

src/main/java/seedu/address/ui/CourseMateListPanel.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

Fix main window resizing issues

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/EditCourseMateDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/testutil/CourseMateUtil.java
src/test/java/seedu/address/testutil/EditCourseMateDescriptorBuilder.java

Remove functionality to edit skills in the edit command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/SimilarNameCommand.java
src/main/java/seedu/address/model/coursemate/UniqueCourseMateList.java
src/test/java/seedu/address/logic/commands/AddMemberCommandTest.java
src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteMemberCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteSkillCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
src/test/java/seedu/address/logic/commands/SimilarNameCommandTest.java
src/test/java/seedu/address/testutil/TypicalCourseMates.java
src/test/java/seedu/address/testutil/TypicalGroups.java

Added:
Substring search for add-member and delete-member. The list also updates if there are more than 1 coursemates found, displaying the coursemates that have similar names. 
Close #110

V1.3 substring search

---

src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/group/Group.java
src/main/java/seedu/address/model/group/TelegramChat.java
src/main/java/seedu/address/storage/JsonAdaptedGroup.java
src/main/java/seedu/address/ui/GroupListCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/GroupListCard.fxml
src/test/data/JsonGroupListStorageTest/invalidAndValidGroupGroupList.json
src/test/data/JsonGroupListStorageTest/invalidGroupGroupList.json
src/test/data/JsonSerializableGroupListTest/duplicateGroupGroupList.json
src/test/data/JsonSerializableGroupListTest/invalidGroupGroupList.json
src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java
src/test/java/seedu/address/logic/parser/CreateGroupCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditGroupCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/model/group/TelegramChatTest.java
src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java

Closes #54 Closes #55 Closes #56 Closes #57

Support telegram group chat

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java

Add warning message for new skills

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

Closes #114 
Fixed the preloaded skillset from "friends", "family" etc, to relevant skills "C++", "Java" etc.
Added a sample group set.

Fix preloaded skills and group

---

src/main/java/seedu/address/logic/commands/RateMateCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/RateMateCommandParser.java
src/main/java/seedu/address/model/coursemate/CourseMate.java
src/main/java/seedu/address/model/coursemate/Rating.java
src/test/java/seedu/address/logic/commands/RateMateCommandTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/RateMateCommandParserTest.java
src/test/java/seedu/address/model/coursemate/CourseMateTest.java
src/test/java/seedu/address/model/coursemate/RateMateTest.java

Closes #112 
Only the model and logic.
Ui to be implemented later in #134

Add rate-mate feature [Logic & Model]

---

src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java
src/main/java/seedu/address/logic/parser/AddMemberCommandParser.java
src/main/java/seedu/address/logic/parser/AddSkillCommandParser.java
src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/RequireSkillCommandParser.java
src/main/java/seedu/address/logic/parser/UnrequireSkillCommandParser.java
src/main/java/seedu/address/model/group/Group.java
src/main/java/seedu/address/model/skill/Skill.java
src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
src/test/java/seedu/address/logic/commands/RequireSkillCommandTest.java
src/test/java/seedu/address/logic/commands/UnrequireSkillCommandTest.java
src/test/java/seedu/address/logic/parser/CreateGroupCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/logic/parser/RequireSkillCommandParserTest.java
src/test/java/seedu/address/logic/parser/UnrequireSkillCommandParserTest.java
src/test/java/seedu/address/model/group/GroupTest.java

Add the require-skill and unrequire-skill commands

---

src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/logic/commands/MarkImportantCommand.java
src/main/java/seedu/address/logic/commands/UnmarkImportantCommand.java
src/main/java/seedu/address/logic/parser/MarkImportantCommandParser.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/UnmarkImportantCommandParser.java
src/main/java/seedu/address/model/skill/Skill.java
src/main/java/seedu/address/storage/JsonAdaptedSkill.java
src/main/java/seedu/address/ui/GroupListCard.java
src/test/data/JsonGroupListStorageTest/invalidAndValidGroupGroupList.json
src/test/data/JsonGroupListStorageTest/invalidGroupGroupList.json
src/test/data/JsonSerializableContactListTest/duplicateCourseMateContactList.json
src/test/data/JsonSerializableContactListTest/typicalCourseMatesContactList.json
src/test/data/JsonSerializableGroupListTest/duplicateGroupGroupList.json
src/test/data/JsonSerializableGroupListTest/invalidGroupGroupList.json
src/test/java/seedu/address/logic/commands/MarkImportantCommandTest.java
src/test/java/seedu/address/logic/commands/UnmarkImportantCommandTest.java
src/test/java/seedu/address/logic/parser/AddSkillCommandParserTest.java
src/test/java/seedu/address/logic/parser/DeleteSkillCommandParserTest.java
src/test/java/seedu/address/logic/parser/MarkImportantParserCommandTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/UnmarkImportantParserCommandTest.java
src/test/java/seedu/address/testutil/MarkImportantDescriptorBuilder.java
src/test/java/seedu/address/testutil/UnmarkImportantDescriptorBuilder.java

Added marking and unmarking important skills functionality
[!] at the front signifies that it is an important skill
Closes #72 
Closes #73

Marking and unmarking important skills command

---

src/main/java/seedu/address/model/coursemate/Rating.java
src/main/java/seedu/address/storage/JsonAdaptedCourseMate.java
src/main/java/seedu/address/ui/CourseMateCard.java
src/main/java/seedu/address/ui/CourseMateDetailPanel.java
src/main/resources/view/CourseMateDetailPanel.fxml
src/main/resources/view/CourseMateListCard.fxml
src/test/data/JsonSerializableContactListTest/duplicateCourseMateContactList.json
src/test/data/JsonSerializableContactListTest/invalidCourseMateContactList.json
src/test/data/JsonSerializableContactListTest/typicalCourseMatesContactList.json
src/test/data/JsonSerializableGroupListTest/duplicateGroupGroupList.json
src/test/data/JsonSerializableGroupListTest/invalidGroupGroupList.json
src/test/java/seedu/address/storage/JsonAdaptedCourseMateTest.java
src/test/java/seedu/address/testutil/CourseMateBuilder.java
src/test/java/seedu/address/testutil/TypicalCourseMates.java

Show rating stars & hide teleid box and rating box if null or zero

---

src/main/java/seedu/address/logic/commands/ConfirmCommandUtils.java
src/main/java/seedu/address/logic/commands/ConfirmMemberCommand.java
src/main/java/seedu/address/logic/commands/MarkImportantCommand.java
src/main/java/seedu/address/logic/commands/RateMateCommand.java
src/main/java/seedu/address/logic/commands/UnconfirmMemberCommand.java
src/main/java/seedu/address/logic/parser/ConfirmMemberCommandParser.java
src/main/java/seedu/address/logic/parser/MatchMateParser.java
src/main/java/seedu/address/logic/parser/UnconfirmMemberCommandParser.java
src/main/java/seedu/address/model/coursemate/CourseMate.java
src/main/java/seedu/address/storage/JsonAdaptedCourseMate.java
src/main/java/seedu/address/ui/GroupListCard.java
src/main/resources/view/DarkTheme.css
src/test/java/seedu/address/logic/commands/ConfirmMemberCommandTest.java
src/test/java/seedu/address/logic/commands/UnconfirmMemberCommandTest.java
src/test/java/seedu/address/logic/parser/ConfirmMemberCommandParserTest.java
src/test/java/seedu/address/logic/parser/DeleteMemberCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchMateParserTest.java
src/test/java/seedu/address/logic/parser/RateMateCommandParserTest.java
src/test/java/seedu/address/logic/parser/UnconfirmMemberCommandParserTest.java
src/test/java/seedu/address/model/coursemate/CourseMateTest.java
src/test/java/seedu/address/storage/JsonAdaptedCourseMateTest.java
src/test/java/seedu/address/testutil/CourseMateBuilder.java

Closes #113 
Tests to be written later in #150
Edit: Wrote tests, now it also closes #150

Set team members to be unknown/confirmed

---

src/main/resources/view/CourseMateDetailPanel.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/GroupListCard.fxml
src/main/resources/view/HelpWindow.css
src/main/resources/view/MainWindow.fxml

Closes #175 Closes #160 Closes #158 Closes #157

Fix cosmetic bugs in UI

---

src/main/java/seedu/address/model/coursemate/TelegramHandle.java

Restrict maximum length of telegram handles

---

src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/RateMateCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java

Change help messages to include multiplicities, also fix bracket notation for rate-mate

---

src/main/java/seedu/address/ui/HelpWindow.java

Change the help link to reflect the new user guide

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java

Closes #154
Closes #159 
Closes #161 
Closes #172

Fix error messages for add, similarName, edit, and addMember commands

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditGroupCommand.java

Rename edit group command

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/model/GroupList.java
src/test/java/seedu/address/model/GroupListTest.java

This is done by creating copy Groups when edits of coursemates or skills are made
Closes #139

Force rerender of Group list panel when needed

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/CourseMateDetailPanel.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

Fix coursemate detail panel behavior when coursemate gets deleted

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/RateMateCommand.java

Fix usage messages for rate-mate, find-mate, and find-group command

---

docs/UserGuide.md

[UG] Update find-mate, find-group & rate-mate command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java

also change NAME to GROUP_NAME when relevant
Closes #144

Add require-skill and unrequire-skill in the UG

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java

Reverts AY2324S2-CS2103T-F13-3/tp#200

Revert "Add require-skill and unrequire-skill in the UG"

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditGroupCommand.java
src/main/java/seedu/address/logic/commands/MarkImportantCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnmarkImportantCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java

Closes #173 
Closes #171 
Closes #147

Add mark-important and unmark-important to User Guide

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddMemberCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/logic/commands/UnrequireSkillCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
src/main/java/seedu/address/logic/parser/SuggestMateCommandParser.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/RequireSkillCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditGroupCommandParserTest.java
src/test/java/seedu/address/logic/parser/SuggestMateCommandParserTest.java

Closes #166 
Closes #155 
Closes #168 
Tests for require-skill getNewSkills function are not made yet, but this is fine for now (UPD: Added tests)

Improve error messages and detect new skills for group list operations

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/RateMateCommand.java
src/main/java/seedu/address/model/coursemate/Name.java
src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteSkillCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/model/coursemate/CourseMateTest.java

Closes #162 
Closes #165 
Closes #170

Persist filter list predicate, fix name error (capitalization and alias)

---

docs/UserGuide.md

Modify storage description in UserGuide.md

---

src/main/java/seedu/address/MainApp.java

Modify saving so that the file uses either all sample data or all blank data

---

docs/DeveloperGuide.md
docs/UserGuide.md

Planned enhancements: Closes #218  Closes #221  Closes #245  Closes #250  Closes #256  
User guide bugs: Closes #217  Closes #227  Closes #238  Closes #263 
DG task: Closes #288

Fix bugs in user guide and developer guide

---

src/main/resources/view/GroupListCard.fxml

Make the group list panel horizontally scrollable

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddSkillCommand.java
src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
src/main/java/seedu/address/logic/commands/RequireSkillCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java

Create-group no longer has unexpected behavior when multiple members with similar names are added

---

docs/DeveloperGuide.md
docs/diagrams/GroupClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Add DG section regarding the new `Model` class

---

docs/DeveloperGuide.md
docs/diagrams/GroupClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Closes #286 
Slight modification to the Group class diagram

Update class diagrams for Model & Logic

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/skill/Skill.java

Change ! symbol to unicode +2757 and change skills to only accept ascii characters

---

docs/DeveloperGuide.md
src/main/java/seedu/address/model/coursemate/Rating.java

Update use cases in DG

---

docs/DeveloperGuide.md

Slight modifiction to NFR & Glossary

---

docs/DeveloperGuide.md

Fix typos and notation issues for DG Appendix sections
